### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by mzprose** [huangeddie/style-transfer-quality#10]
Where is the pytorch version?

**Comment by mzprose** [comment]
I found it, sorry, I didn't pay attention before.

**Comment by Max-Well-Wang** [comment]
Could you please tell me where is the pytorch version? I can not find it

**Comment by C00reNUT** [comment]
> Could you please tell me where is the pytorch version? I can not find it

https://github.com/aigagror/style-transfer-quality/tree/pytorch
