### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by mzprose** [huangeddie/style-transfer-quality#11]
In the pytorch version, line 45 of style/steps.py, why the input is gen_img instead of style_img+gen_img, the args.distance I chose is wgan-gp

**Comment by huangeddie** [comment]
`sc_step` simply computes the style loss and content loss. It does not optimize the discriminator in wgan-gp, so there is no need for style_img.

I think what you're looking for is `disc_step` in the same file. It uses both gen_img and style_img.
