### ISSUE TITLE
Tanh

### ISSUE THREAD

**Issue by mzprose** [huangeddie/style-transfer-quality#13]
In code ,I didn't find this part of Tanh,where it is exists?

**Comment by huangeddie** [comment]
I've replaced Tanh with normalizing the features to 0-mean and unit variance with respect to the style features.
I found this to work even better

**Comment by mzprose** [comment]
It turned out to be the case, thank you for your reply, but I have another question, whether you can use a batch of data to get their features, and then use these features as a distribution. Have you considered？

**Comment by huangeddie** [comment]
Are you saying use multiple images to represent style? I've never tried it, but I think that's possible. I don't know what the results would be like though
